artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data
  source_file: data/heart.csv
  raw_data_path: artifacts/data/data.csv
  train_data_path: artifacts/data/train.csv
  test_data_path: artifacts/data/test.csv

data_transformation:
  root_dir: artifacts/preprocessing
  preprocessor_path: artifacts/preprocessing/preprocessor.pkl

model_trainer:
  root_dir: artifacts/models
  trained_model_path: artifacts/models/model.pkl